# .github/release.yml

changelog:
  exclude:
    labels:
      - notes:ignore
  categories:
    - title: Controller Changes
      labels:
        - notes:zt-controller
    - title: Router Changes
      labels:
        - notes:zt-router
    - title: Tunneler Daemonset Changes
      labels:
        - notes:zt-edge-tunnel
    - title: Hosting Pod Changes
      labels:
        - notes:zt-host
    - title: zrok Changes
      labels:
        - notes:zrok
    - title: BrowZer Bootstrapper Changes
      labels:
        - notes:zt-browzer-bootstrapper
    - title: Other Changes
      labels:
        - "*"
